# Connection to MySQL Server

In [ ]:
import mysql.connector

# connecting to MySQL Server

conn = mysql.connector.connect(
        host="localhost", 
        user="root",
        password="password" # Use your password here
    )
cursor = conn.cursor()
cursor

# Creating Database 'Traffic_Crashes_Data'

In [2]:
# Creating Traffic_Crashes_Data Database

cursor.execute('CREATE DATABASE IF NOT EXISTS Traffic_Crashes_Data')
conn.commit()

# Reading the CSV file and convert as DataFrame

In [ ]:
import pandas as pd

# Reading the Traffic_CrashesData csv file

# Use your file path here

path = r"/home/rajesh-vijayakumar/Desktop/GUVI_AIML/Traffic_Crash_Analytics_and_Safety_Intelligence_Platform/data/processed/Traffic_CrashesData.csv"

# Convert csv file to Dataframe

df = pd.read_csv(path)

# Displaying Dataframe information

df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 660934 entries, 0 to 660933
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH_RECORD_ID                660934 non-null  str
 1   CRASH_DATE                     660934 non-null  str
 2   POSTED_SPEED_LIMIT             660934 non-null  int64
 3   TRAFFIC_CONTROL_DEVICE         660934 non-null  str
 4   DEVICE_CONDITION               660934 non-null  str
 5   WEATHER_CONDITION              660934 non-null  str
 6   LIGHTING_CONDITION             660934 non-null  str
 7   FIRST_CRASH_TYPE               660934 non-null  str
 8   TRAFFICWAY_TYPE                660934 non-null  str
 9   ALIGNMENT                      660934 non-null  str
 10  ROADWAY_SURFACE_COND           660934 non-null  str
 11  ROAD_DEFECT                    660934 non-null  str
 12  REPORT_TYPE                    660934 non-null  str
 13  CRASH_TYPE                     660934 non-null  str
 14  DAMAGE                         660934 non-null  str
 15  DATE_POLICE_NOTIFIED           660934 non-null  str
 16  PRIM_CONTRIBUTORY_CAUSE        660934 non-null  str
 17  SEC_CONTRIBUTORY_CAUSE         660934 non-null  str
 18  STREET_NO                      660934 non-null  int64
 19  STREET_DIRECTION               660934 non-null  str
 20  STREET_NAME                    660934 non-null  str
 21  BEAT_OF_OCCURRENCE             660934 non-null  float64
 22  NUM_UNITS                      660934 non-null  int64
 23  MOST_SEVERE_INJURY             660934 non-null  str
 24  INJURIES_TOTAL                 660934 non-null  float64
 25  INJURIES_FATAL                 660934 non-null  float64
 26  INJURIES_INCAPACITATING        660934 non-null  float64
 27  INJURIES_NON_INCAPACITATING    660934 non-null  float64
 28  INJURIES_REPORTED_NOT_EVIDENT  660934 non-null  float64
 29  INJURIES_NO_INDICATION         660934 non-null  float64
 30  INJURIES_UNKNOWN               660934 non-null  float64
 31  CRASH_HOUR                     660934 non-null  int64
 32  CRASH_DAY_OF_WEEK              660934 non-null  int64
 33  CRASH_MONTH                    660934 non-null  int64
 34  LATITUDE                       660934 non-null  float64
 35  LONGITUDE                      660934 non-null  float64
 36  LOCATION                       660934 non-null  str
 37  date                           660934 non-null  str
 38  year                           660934 non-null  int64
dtypes: float64(10), int64(7), str(22)
memory usage: 488.0 MB

,CRASH_RECORD_ID,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,ALIGNMENT,...,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION,date,year
0,000c4307d8e9b39075cffdd0aade3603e0f96f14e41da9...,01/14/2025 12:25:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,SIDESWIPE SAME DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,2.0,0.0,12,3,1,41.997808,-87.655770,POINT (-87.655770494712 41.997807727633),2025-01-14 12:25:00,2025
1,027b0b4c21460d3441fd83929abb9673c6fc0c7d575675...,05/23/2025 09:30:00 AM,30,STOP SIGN/FLASHER,UNKNOWN,UNKNOWN,DAYLIGHT,TURNING,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,2.0,0.0,9,6,5,41.946529,-87.688106,POINT (-87.688106391039 41.946529480518),2025-05-23 09:30:00,2025
2,04d91dffc94f677358ca47056921ba5c4224320df27ed4...,04/05/2025 08:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,UNKNOWN,PARKED MOTOR VEHICLE,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,20,7,4,41.899325,-87.715074,POINT (-87.715074373867 41.899324573751),2025-04-05 20:00:00,2025
3,0b5603954d84b7341c7cad4f570ea039e85919f3750ccb...,05/23/2025 09:15:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,STRAIGHT AND LEVEL,...,2.0,0.0,9,6,5,41.902793,-87.699412,POINT (-87.699412181285 41.902792968177),2025-05-23 09:15:00,2025
4,00bce77960c2faa2a8782a8cac1d6e5715802d6c072a08...,01/14/2025 08:00:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,SNOW,DAYLIGHT,REAR END,FOUR WAY,STRAIGHT AND LEVEL,...,2.0,0.0,8,3,1,41.691207,-87.720555,POINT (-87.720554863466 41.691206664451),2025-01-14 08:00:00,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660929,5ff5b050ae2079df6addca8431c1bd6e381432ff72ff43...,10/18/2025 11:42:00 AM,35,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLOUDY/OVERCAST,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,11,7,10,41.938537,-87.835965,POINT (-87.835965097138 41.938536628877),2025-10-18 11:42:00,2025
660930,7a7963ac15a38f3cf7549397dd053fd7612dd5194de280...,10/18/2025 03:50:00 AM,35,NO CONTROLS,NO CONTROLS,RAIN,DARKNESS,FIXED OBJECT,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,3,7,10,41.899200,-87.618841,POINT (-87.618840672611 41.8992002546),2025-10-18 03:50:00,2025
660931,84e546c12fd8fd78ae4e2dc26fdb02d6e8f6c4c92be450...,10/18/2025 05:08:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,5.0,0.0,17,7,10,41.848081,-87.675881,POINT (-87.675881338024 41.848080595588),2025-10-18 17:08:00,2025
660932,8237045757e7fed5adfb450bd7c8472e28a61d322f86bb...,10/19/2025 01:50:00 AM,30,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,REAR TO FRONT,NOT DIVIDED,STRAIGHT AND LEVEL,...,5.0,0.0,1,1,10,41.949157,-87.648527,POINT (-87.648526617888 41.949157243366),2025-10-19 01:50:00,2025
660933,ede74fa6fd507334cd0415d3d53deb535d27d23523cd38...,06/23/2023 04:30:00 PM,30,UNKNOWN,UNKNOWN,UNKNOWN,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,...,1.0,0.0,16,6,6,42.004564,-87.709200,POINT (-87.709200383599 42.004564031467),2023-06-23 16:30:00,2023

### Finding maximum length of column with type String and maximum value of column with type Integer and Float

In [4]:
cols = df.columns
print('Column Name : maximum (length / value) of Data \n')
for c in cols:
    if df[c].dtype == 'str':

        # Finding mamimum length of String of the Column

        x=df[c].unique()
        max_len = 0
        for y in x:
            if len(y) >= max_len:
                max_len = len(y)
        print(c,': (string)',max_len)

    elif df[c].dtype == float:

        # Finding maximum value of the Column with the type 'float'

        x=df[c].unique()
        max = 0
        for y in x:
            y **= 2
            y **= 0.5
            if y >= max:
                max = y
        print(c,': (float)',max)

    elif df[c].dtype == int:

        # Finding maximum value of the Column with the type 'int'
        x=df[c].unique()
        max = 0
        for y in x:
            if y >= max:
                max = y
        print(c,': (int)',max)

Column Name : maximum (length / value) of Data

CRASH_RECORD_ID : (string) 128
CRASH_DATE : (string) 22
POSTED_SPEED_LIMIT : (int) 70
TRAFFIC_CONTROL_DEVICE : (string) 24
DEVICE_CONDITION : (string) 24
WEATHER_CONDITION : (string) 24
LIGHTING_CONDITION : (string) 22
FIRST_CRASH_TYPE : (string) 28
TRAFFICWAY_TYPE : (string) 31
ALIGNMENT : (string) 21
ROADWAY_SURFACE_COND : (string) 15
ROAD_DEFECT : (string) 17
REPORT_TYPE : (string) 26
CRASH_TYPE : (string) 32
DAMAGE : (string) 13
DATE_POLICE_NOTIFIED : (string) 22
PRIM_CONTRIBUTORY_CAUSE : (string) 80
SEC_CONTRIBUTORY_CAUSE : (string) 80
STREET_NO : (int) 13799
STREET_DIRECTION : (string) 1
STREET_NAME : (string) 27
BEAT_OF_OCCURRENCE : (float) 13799
NUM_UNITS : (int) 18
MOST_SEVERE_INJURY : (string) 24
INJURIES_TOTAL : (float) 21.0
INJURIES_FATAL : (float) 21.0
INJURIES_INCAPACITATING : (float) 21.0
INJURIES_NON_INCAPACITATING : (float) 21.0
INJURIES_REPORTED_NOT_EVIDENT : (float) 21.0
INJURIES_NO_INDICATION : (float) 49.0
INJURIES_UNKNOWN : (float) 49.0
CRASH_HOUR : (int) 23
CRASH_DAY_OF_WEEK : (int) 7
CRASH_MONTH : (int) 12
LATITUDE : (float) 42.0227798611
LONGITUDE : (float) 87.9396778197
LOCATION : (string) 40
date : (string) 19
year : (int) 2026

### Function to make Connection to Traffic_Crashes_Data Database

In [5]:
import mysql.connector

# Function to make Connection to Traffic_Crashes_Data Database

def makeConnection():
    conn = mysql.connector.connect(
        host="localhost", 
        user="root",
        password="Bakkiyam@03", # Use your password here
        database="Traffic_Crashes_Data"
    )
    return conn
connection = makeConnection()
print('Database connected Successfully!')

Database connected Successfully!

# Creating the Table

In [6]:
connection = makeConnection()
cursor = connection.cursor()

# Creating table Traffic_Crashes_Analysis if not exists in the Database

query = """CREATE TABLE IF NOT EXISTS Traffic_Crashes_Analysis(
                                    CRASH_RECORD_ID varchar(128),
                                    CRASH_DATE varchar(22),
                                    POSTED_SPEED_LIMIT int,
                                    TRAFFIC_CONTROL_DEVICE varchar(24),
                                    DEVICE_CONDITION varchar(24),
                                    WEATHER_CONDITION varchar(24),
                                    LIGHTING_CONDITION varchar(22),
                                    FIRST_CRASH_TYPE varchar(28),
                                    TRAFFICWAY_TYPE varchar(31),
                                    ALIGNMENT varchar(21),
                                    ROADWAY_SURFACE_COND varchar(15),
                                    ROAD_DEFECT varchar(17),
                                    REPORT_TYPE varchar(26),
                                    CRASH_TYPE varchar(32),
                                    DAMAGE varchar(13),
                                    DATE_POLICE_NOTIFIED varchar(22),
                                    PRIM_CONTRIBUTORY_CAUSE varchar(80),
                                    SEC_CONTRIBUTORY_CAUSE varchar(80),
                                    STREET_NO int,
                                    STREET_DIRECTION varchar(1),
                                    STREET_NAME varchar(27),
                                    BEAT_OF_OCCURRENCE float,
                                    NUM_UNITS int,
                                    MOST_SEVERE_INJURY varchar(24),
                                    INJURIES_TOTAL float,
                                    INJURIES_FATAL float,
                                    INJURIES_INCAPACITATING float,
                                    INJURIES_NON_INCAPACITATING float,
                                    INJURIES_REPORTED_NOT_EVIDENT float,
                                    INJURIES_NO_INDICATION float,
                                    INJURIES_UNKNOWN float,
                                    CRASH_HOUR int,
                                    CRASH_DAY_OF_WEEK int,
                                    CRASH_MONTH int,
                                    LATITUDE double,
                                    LONGITUDE double,
                                    LOCATION varchar(40),
                                    date varchar(19),
                                    year int
                                )"""
cursor.execute(query)
connection.commit()

# Inserting the Data from DataFrame to MySQL

In [ ]:
connection = makeConnection()
cursor = connection.cursor()

# Query to insert the Data to the Table in the Database

query = """insert into Traffic_Crashes_Analysis(
                                    CRASH_RECORD_ID,
                                    CRASH_DATE,
                                    POSTED_SPEED_LIMIT,
                                    TRAFFIC_CONTROL_DEVICE,
                                    DEVICE_CONDITION,
                                    WEATHER_CONDITION,
                                    LIGHTING_CONDITION,
                                    FIRST_CRASH_TYPE,
                                    TRAFFICWAY_TYPE,
                                    ALIGNMENT,
                                    ROADWAY_SURFACE_COND,
                                    ROAD_DEFECT,
                                    REPORT_TYPE,
                                    CRASH_TYPE,
                                    DAMAGE,
                                    DATE_POLICE_NOTIFIED,
                                    PRIM_CONTRIBUTORY_CAUSE,
                                    SEC_CONTRIBUTORY_CAUSE,
                                    STREET_NO,
                                    STREET_DIRECTION,
                                    STREET_NAME,
                                    BEAT_OF_OCCURRENCE,
                                    NUM_UNITS,
                                    MOST_SEVERE_INJURY,
                                    INJURIES_TOTAL,
                                    INJURIES_FATAL,
                                    INJURIES_INCAPACITATING,
                                    INJURIES_NON_INCAPACITATING,
                                    INJURIES_REPORTED_NOT_EVIDENT,
                                    INJURIES_NO_INDICATION,
                                    INJURIES_UNKNOWN,
                                    CRASH_HOUR,
                                    CRASH_DAY_OF_WEEK,
                                    CRASH_MONTH,
                                    LATITUDE,
                                    LONGITUDE,
                                    LOCATION,
                                    date,
                                    year
                                ) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""

# Inserting the Data from the Dataframe to the Table in the Database

for row in df.itertuples():
    cursor.execute(query,(row[1],
                          row[2],
                          row[3],
                          row[4],
                          row[5],
                          row[6],
                          row[7],
                          row[8],
                          row[9],
                          row[10],
                          row[11],
                          row[12],
                          row[13],
                          row[14],
                          row[15],
                          row[16],
                          row[17],
                          row[18],
                          row[19],
                          row[20],
                          row[21],
                          row[22],
                          row[23],
                          row[24],
                          row[25],
                          row[26],
                          row[27],
                          row[28],
                          row[29],
                          row[30],
                          row[31],
                          row[32],
                          row[33],
                          row[34],
                          row[35],
                          row[36],
                          row[37],
                          row[38],
                          row[39]))
connection.commit()

### Another method to insert Data from Dataframe to the Table in Database

In [ ]:
connection = makeConnection()
cursor = connection.cursor()

# Query to insert the Data to the Table in the Database

query = """insert into Traffic_Crashes_Analysis(
                                    CRASH_RECORD_ID,
                                    CRASH_DATE,
                                    POSTED_SPEED_LIMIT,
                                    TRAFFIC_CONTROL_DEVICE,
                                    DEVICE_CONDITION,
                                    WEATHER_CONDITION,
                                    LIGHTING_CONDITION,
                                    FIRST_CRASH_TYPE,
                                    TRAFFICWAY_TYPE,
                                    ALIGNMENT,
                                    ROADWAY_SURFACE_COND,
                                    ROAD_DEFECT,
                                    REPORT_TYPE,
                                    CRASH_TYPE,
                                    DAMAGE,
                                    DATE_POLICE_NOTIFIED,
                                    PRIM_CONTRIBUTORY_CAUSE,
                                    SEC_CONTRIBUTORY_CAUSE,
                                    STREET_NO,
                                    STREET_DIRECTION,
                                    STREET_NAME,
                                    BEAT_OF_OCCURRENCE,
                                    NUM_UNITS,
                                    MOST_SEVERE_INJURY,
                                    INJURIES_TOTAL,
                                    INJURIES_FATAL,
                                    INJURIES_INCAPACITATING,
                                    INJURIES_NON_INCAPACITATING,
                                    INJURIES_REPORTED_NOT_EVIDENT,
                                    INJURIES_NO_INDICATION,
                                    INJURIES_UNKNOWN,
                                    CRASH_HOUR,
                                    CRASH_DAY_OF_WEEK,
                                    CRASH_MONTH,
                                    LATITUDE,
                                    LONGITUDE,
                                    LOCATION,
                                    date,
                                    year
                                ) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""

# Inserting the Data from the Dataframe to the Table in the Database

for row in df.itertuples():
    cursor.execute(query,(row.CRASH_RECORD_ID,
                          row.CRASH_DATE,
                          row.POSTED_SPEED_LIMIT,
                          row.TRAFFIC_CONTROL_DEVICE,
                          row.DEVICE_CONDITION,
                          row.WEATHER_CONDITION,
                          row.LIGHTING_CONDITION,
                          row.FIRST_CRASH_TYPE,
                          row.TRAFFICWAY_TYPE,
                          row.ALIGNMENT,
                          row.ROADWAY_SURFACE_COND,
                          row.ROAD_DEFECT,
                          row.REPORT_TYPE,
                          row.CRASH_TYPE,
                          row.DAMAGE,
                          row.DATE_POLICE_NOTIFIED,
                          row.PRIM_CONTRIBUTORY_CAUSE,
                          row.SEC_CONTRIBUTORY_CAUSE,
                          row.STREET_NO,
                          row.STREET_DIRECTION,
                          row.STREET_NAME,
                          row.BEAT_OF_OCCURRENCE,
                          row.NUM_UNITS,
                          row.MOST_SEVERE_INJURY,
                          row.INJURIES_TOTAL,
                          row.INJURIES_FATAL,
                          row.INJURIES_INCAPACITATING,
                          row.INJURIES_NON_INCAPACITATING,
                          row.INJURIES_REPORTED_NOT_EVIDENT,
                          row.INJURIES_NO_INDICATION,
                          row.INJURIES_UNKNOWN,
                          row.CRASH_HOUR,
                          row.CRASH_DAY_OF_WEEK,
                          row.CRASH_MONTH,
                          row.LATITUDE,
                          row.LONGITUDE,
                          row.LOCATION,
                          row.date,
                          row.year))
connection.commit()

In [7]:
# Code to describe the Table

connection = makeConnection()
cursor = connection.cursor()
query = "DESCRIBE Traffic_Crashes_Analysis"
cursor.execute(query)
for col in cursor:
    print(col[0:2])

('CRASH_RECORD_ID', 'varchar(128)')
('CRASH_DATE', 'varchar(22)')
('POSTED_SPEED_LIMIT', 'int')
('TRAFFIC_CONTROL_DEVICE', 'varchar(24)')
('DEVICE_CONDITION', 'varchar(24)')
('WEATHER_CONDITION', 'varchar(24)')
('LIGHTING_CONDITION', 'varchar(22)')
('FIRST_CRASH_TYPE', 'varchar(28)')
('TRAFFICWAY_TYPE', 'varchar(31)')
('ALIGNMENT', 'varchar(21)')
('ROADWAY_SURFACE_COND', 'varchar(15)')
('ROAD_DEFECT', 'varchar(17)')
('REPORT_TYPE', 'varchar(26)')
('CRASH_TYPE', 'varchar(32)')
('DAMAGE', 'varchar(13)')
('DATE_POLICE_NOTIFIED', 'varchar(22)')
('PRIM_CONTRIBUTORY_CAUSE', 'varchar(80)')
('SEC_CONTRIBUTORY_CAUSE', 'varchar(80)')
('STREET_NO', 'int')
('STREET_DIRECTION', 'varchar(1)')
('STREET_NAME', 'varchar(27)')
('BEAT_OF_OCCURRENCE', 'float')
('NUM_UNITS', 'int')
('MOST_SEVERE_INJURY', 'varchar(24)')
('INJURIES_TOTAL', 'float')
('INJURIES_FATAL', 'float')
('INJURIES_INCAPACITATING', 'float')
('INJURIES_NON_INCAPACITATING', 'float')
('INJURIES_REPORTED_NOT_EVIDENT', 'float')
('INJURIES_NO_INDICATION', 'float')
('INJURIES_UNKNOWN', 'float')
('CRASH_HOUR', 'int')
('CRASH_DAY_OF_WEEK', 'int')
('CRASH_MONTH', 'int')
('LATITUDE', 'double')
('LONGITUDE', 'double')
('LOCATION', 'varchar(40)')
('date', 'varchar(19)')
('year', 'int')

In [8]:
# Code to see the total number of records in the Table

connection = makeConnection()
cursor = connection.cursor()
query = "SELECT COUNT(*) FROM Traffic_Crashes_Analysis"
cursor.execute(query)
result = cursor.fetchone()
row_count = result[0]
row_count

660934

In [9]:
# Code to get information about the columns returned by SQL Query

cursor.execute('SELECT * FROM Traffic_Crashes_Analysis')
cursor.description

[('CRASH_RECORD_ID', 253, None, None, None, None, 1, 0, 255),
 ('CRASH_DATE', 253, None, None, None, None, 1, 0, 255),
 ('POSTED_SPEED_LIMIT', 3, None, None, None, None, 1, 32768, 63),
 ('TRAFFIC_CONTROL_DEVICE', 253, None, None, None, None, 1, 0, 255),
 ('DEVICE_CONDITION', 253, None, None, None, None, 1, 0, 255),
 ('WEATHER_CONDITION', 253, None, None, None, None, 1, 0, 255),
 ('LIGHTING_CONDITION', 253, None, None, None, None, 1, 0, 255),
 ('FIRST_CRASH_TYPE', 253, None, None, None, None, 1, 0, 255),
 ('TRAFFICWAY_TYPE', 253, None, None, None, None, 1, 0, 255),
 ('ALIGNMENT', 253, None, None, None, None, 1, 0, 255),
 ('ROADWAY_SURFACE_COND', 253, None, None, None, None, 1, 0, 255),
 ('ROAD_DEFECT', 253, None, None, None, None, 1, 0, 255),
 ('REPORT_TYPE', 253, None, None, None, None, 1, 0, 255),
 ('CRASH_TYPE', 253, None, None, None, None, 1, 0, 255),
 ('DAMAGE', 253, None, None, None, None, 1, 0, 255),
 ('DATE_POLICE_NOTIFIED', 253, None, None, None, None, 1, 0, 255),
 ('PRIM_CONTRIBUTORY_CAUSE', 253, None, None, None, None, 1, 0, 255),
 ('SEC_CONTRIBUTORY_CAUSE', 253, None, None, None, None, 1, 0, 255),
 ('STREET_NO', 3, None, None, None, None, 1, 32768, 63),
 ('STREET_DIRECTION', 253, None, None, None, None, 1, 0, 255),
 ('STREET_NAME', 253, None, None, None, None, 1, 0, 255),
 ('BEAT_OF_OCCURRENCE', 4, None, None, None, None, 1, 32768, 63),
 ('NUM_UNITS', 3, None, None, None, None, 1, 32768, 63),
 ('MOST_SEVERE_INJURY', 253, None, None, None, None, 1, 0, 255),
 ('INJURIES_TOTAL', 4, None, None, None, None, 1, 32768, 63),
 ('INJURIES_FATAL', 4, None, None, None, None, 1, 32768, 63),
 ('INJURIES_INCAPACITATING', 4, None, None, None, None, 1, 32768, 63),
 ('INJURIES_NON_INCAPACITATING', 4, None, None, None, None, 1, 32768, 63),
 ('INJURIES_REPORTED_NOT_EVIDENT', 4, None, None, None, None, 1, 32768, 63),
 ('INJURIES_NO_INDICATION', 4, None, None, None, None, 1, 32768, 63),
 ('INJURIES_UNKNOWN', 4, None, None, None, None, 1, 32768, 63),
 ('CRASH_HOUR', 3, None, None, None, None, 1, 32768, 63),
 ('CRASH_DAY_OF_WEEK', 3, None, None, None, None, 1, 32768, 63),
 ('CRASH_MONTH', 3, None, None, None, None, 1, 32768, 63),
 ('LATITUDE', 5, None, None, None, None, 1, 32768, 63),
 ('LONGITUDE', 5, None, None, None, None, 1, 32768, 63),
 ('LOCATION', 253, None, None, None, None, 1, 0, 255),
 ('date', 253, None, None, None, None, 1, 0, 255),
 ('year', 3, None, None, None, None, 1, 32768, 63)]

### Function to read SQLQuery output, assign column name of database table to dataframe column and rearrange index starts from 1

In [10]:
import pandas as pd
def read_sql(c):
    cursor = c

    # code to get the column names from the SQL Query

    column_names = [desc[0] for desc in cursor.description]
    dict_columns = {}
    i = 0
    for column_name in column_names:

        # code to update column names in a Dictionary

        dict_columns.update({i:column_name})
        i+=1
        
    data_list = []
    for data in cursor:
        data_list.append(data)
    df = pd.DataFrame(data_list)

    # code to rename column names from the Dictionary

    df.rename(columns=dict_columns,inplace=True)

    # code to rearrange row index starts from 1

    df.index += 1
    return df

### 1. Query to find the top 5 most dangerous combinations of weather and crash type based on total crashes.

In [11]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT WEATHER_CONDITION, CRASH_TYPE, COUNT(*) AS TOTAL_CRASHES
        FROM Traffic_Crashes_Analysis
        GROUP BY WEATHER_CONDITION, CRASH_TYPE
        ORDER BY TOTAL_CRASHES DESC
        LIMIT 5'''
cursor.execute(query)
df = read_sql(cursor)
df

  WEATHER_CONDITION                        CRASH_TYPE  TOTAL_CRASHES
1             CLEAR            NO INJURY / DRIVE AWAY         360238
2             CLEAR  INJURY AND / OR TOW DUE TO CRASH         155302
3           UNKNOWN            NO INJURY / DRIVE AWAY          41442
4              RAIN            NO INJURY / DRIVE AWAY          31560
5              RAIN  INJURY AND / OR TOW DUE TO CRASH          19647

### 2. Query to identify the top 10 streets with the highest number of injury crashes.

In [9]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT STREET_NAME, COUNT(*) AS TOTAL_INJURY_CRASHES 
            FROM Traffic_Crashes_Analysis 
            WHERE INJURIES_TOTAL > 0
            GROUP BY STREET_NAME 
            ORDER BY TOTAL_INJURY_CRASHES DESC 
            LIMIT 10'''
cursor.execute(query)
df = read_sql(cursor)
df

         STREET_NAME  TOTAL_INJURY_CRASHES
1        WESTERN AVE                  2973
2         PULASKI RD                  2840
3        ASHLAND AVE                  2579
4         CICERO AVE                  2560
5         HALSTED ST                  2536
6         KEDZIE AVE                  1965
7           STATE ST                  1379
8       MICHIGAN AVE                  1344
9   STONY ISLAND AVE                  1340
10         DAMEN AVE                  1263

### 3. Query to find the percentage of crashes that resulted in injuries for each crash type.

In [10]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT CRASH_TYPE, COUNT(*) AS CRASH_COUNT, COUNT(*) * 100.0 / SUM(COUNT(*)) OVER () AS CRASH_PERCENTAGE
            FROM Traffic_Crashes_Analysis
            WHERE INJURIES_TOTAL > 0
            GROUP BY CRASH_TYPE'''
cursor.execute(query)
df = read_sql(cursor)
df

                         CRASH_TYPE  CRASH_COUNT CRASH_PERCENTAGE
1  INJURY AND / OR TOW DUE TO CRASH       103527         99.22272
2            NO INJURY / DRIVE AWAY          811          0.77728

In [11]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT MOST_SEVERE_INJURY AS INJURY_TYPE, COUNT(*) * 100.0 / SUM(COUNT(*)) OVER () AS CRASH_PERCENTAGE
            FROM Traffic_Crashes_Analysis
            GROUP BY MOST_SEVERE_INJURY'''
cursor.execute(query)
df = read_sql(cursor)
df

                INJURY_TYPE CRASH_PERCENTAGE
1   NO INDICATION OF INJURY         84.44580
2  NONINCAPACITATING INJURY          8.73234
3     REPORTED, NOT EVIDENT          5.03197
4     INCAPACITATING INJURY          1.67203
5                     FATAL          0.11786

### 4. Query to determine the peak crash hour for each month.

In [12]:
connection = makeConnection()
cursor = connection.cursor()
query = '''WITH MonthlyHourCounts AS (    
                SELECT CRASH_MONTH, CRASH_HOUR, COUNT(*) AS CRASH_TOTAL,        
                ROW_NUMBER() OVER (PARTITION BY CRASH_MONTH
                    ORDER BY COUNT(*) DESC) AS ranking
                    FROM Traffic_Crashes_Analysis
                    GROUP BY CRASH_MONTH, CRASH_HOUR)
            SELECT CASE CRASH_MONTH
                        WHEN 1 THEN 'January'
                        WHEN 2 THEN 'February'
                        WHEN 3 THEN 'March'
                        WHEN 4 THEN 'April'
                        WHEN 5 THEN 'May'
                        WHEN 6 THEN 'June'
                        WHEN 7 THEN 'July'
                        WHEN 8 THEN 'August'
                        WHEN 9 THEN 'September'
                        WHEN 10 THEN 'October'
                        WHEN 11 THEN 'November'
                        WHEN 12 THEN 'December'
                    END AS MONTH_OF_CRASH, CRASH_HOUR, CRASH_TOTAL
            FROM MonthlyHourCounts
            WHERE ranking = 1
            ORDER BY CRASH_MONTH'''
cursor.execute(query)
df = read_sql(cursor)
df

   MONTH_OF_CRASH  CRASH_HOUR  CRASH_TOTAL
1         January          15         4408
2        February          15         4525
3           March          15         4610
4           April          15         3884
5             May          15         4727
6            June          16         4552
7            July          16         4299
8          August          16         4504
9       September          15         4597
10        October          15         4644
11       November          17         3782
12       December          17         4117

### 5. Query to find the top 5 primary causes of crashes during night time (CRASH_HOUR ≥ 18).

In [13]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT PRIM_CONTRIBUTORY_CAUSE AS PRIMARY_CAUSE_OF_CRASH, COUNT(*) AS CRASH_TOTAL
            FROM Traffic_Crashes_Analysis
            WHERE CRASH_HOUR >= 18 OR CRASH_HOUR < 6
            GROUP BY PRIM_CONTRIBUTORY_CAUSE
            ORDER BY CRASH_TOTAL DESC
            LIMIT 5'''
cursor.execute(query)
df = read_sql(cursor)
df

                   PRIMARY_CAUSE_OF_CRASH  CRASH_TOTAL
1                     UNABLE TO DETERMINE        93992
2           FAILING TO YIELD RIGHT-OF-WAY        19886
3                   FOLLOWING TOO CLOSELY        15023
4  FAILING TO REDUCE SPEED TO AVOID CRASH        11785
5                          NOT APPLICABLE        11244

### 6. Query to compare average number of injuries in daylight vs darkness conditions.

In [14]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT 
                CASE 
                    WHEN LIGHTING_CONDITION = 'DAYLIGHT' THEN 'Daylight'
                    WHEN LIGHTING_CONDITION LIKE 'DARKNESS%' THEN 'Darkness'
                END 
                AS LIGHTING, 
                COUNT(*) AS TOTAL_CRASHES, 
                ROUND(AVG(INJURIES_TOTAL), 4) AS AVG_INJURIES_PER_CRASH,
                SUM(INJURIES_TOTAL) AS TOTAL_INJURIES
            FROM Traffic_Crashes_Analysis
            WHERE LIGHTING_CONDITION = 'DAYLIGHT' OR LIGHTING_CONDITION LIKE 'DARKNESS%'
            GROUP BY LIGHTING
            ORDER BY AVG_INJURIES_PER_CRASH DESC'''
cursor.execute(query)
df = read_sql(cursor)
df

   LIGHTING  TOTAL_CRASHES  AVG_INJURIES_PER_CRASH  TOTAL_INJURIES
1  Darkness         177858                  0.2745         48815.0
2  Daylight         416853                  0.2071         86311.0

### 7. Query to find which traffic control device type has the highest average injuries per crash.

In [15]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT TRAFFIC_CONTROL_DEVICE, ROUND(AVG(INJURIES_TOTAL),2) AS AVG_INJURIES_PER_CRASH
            FROM Traffic_Crashes_Analysis
            GROUP BY TRAFFIC_CONTROL_DEVICE
            ORDER BY AVG_INJURIES_PER_CRASH DESC
            LIMIT 1'''
cursor.execute(query)
df = read_sql(cursor)
df

  TRAFFIC_CONTROL_DEVICE  AVG_INJURIES_PER_CRASH
1  BICYCLE CROSSING SIGN                    0.66

### 8. Query to identify the top 5 locations (latitude/longitude) with the highest crash frequency.

In [16]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT LATITUDE, LONGITUDE, COUNT(*) AS CRASH_FREQUENCY
            FROM Traffic_Crashes_Analysis
            GROUP BY LATITUDE, LONGITUDE
            ORDER BY CRASH_FREQUENCY DESC
            LIMIT 5'''
cursor.execute(query)
df = read_sql(cursor)
df

    LATITUDE  LONGITUDE  CRASH_FREQUENCY
1  41.976201 -87.905309             1247
2  41.900959 -87.619928              661
3  41.791420 -87.580148              473
4  41.751461 -87.585972              469
5  41.722257 -87.585276              353

### 9. Query to find the top 5 streets with the highest injury rate, considering only streets with more than 100 crashes.

In [17]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT STREET_NAME, 
            	COUNT(*) AS CRASH_TOTAL, 
                SUM(INJURIES_TOTAL) AS TOTAL_INJURIES, 
                ROUND(SUM(INJURIES_TOTAL) * 1.0 / COUNT(*), 2) AS INJURY_RATE
            FROM Traffic_Crashes_Analysis
            GROUP BY STREET_NAME
            HAVING COUNT(*) > 100
            ORDER BY INJURY_RATE DESC
            LIMIT 5'''
cursor.execute(query)
df = read_sql(cursor)
df

         STREET_NAME  CRASH_TOTAL  TOTAL_INJURIES  INJURY_RATE
1       MARQUETTE DR          271           122.0         0.45
2          FIFTH AVE          299           130.0         0.43
3        CORCORAN PL          122            49.0         0.40
4       DOUGLAS BLVD          390           151.0         0.39
5  SOUTH CHICAGO AVE         1710           664.0         0.39

### 10. Query to identify the most common crash type for each year.

In [18]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT year AS YEAR, CRASH_TYPE, CRASH_TOTAL
            FROM (SELECT year, CRASH_TYPE, COUNT(*) AS CRASH_TOTAL, 
                    RANK() OVER (
                        PARTITION BY year
                        ORDER BY COUNT(*) DESC
                    ) AS ranking
                FROM Traffic_Crashes_Analysis
                GROUP BY year, CRASH_TYPE
            ) crash_rank
            WHERE ranking = 1
            ORDER BY year'''
cursor.execute(query)
df = read_sql(cursor)
df

   YEAR              CRASH_TYPE  CRASH_TOTAL
1  2020  NO INJURY / DRIVE AWAY        62706
2  2021  NO INJURY / DRIVE AWAY        74661
3  2022  NO INJURY / DRIVE AWAY        75897
4  2023  NO INJURY / DRIVE AWAY        78034
5  2024  NO INJURY / DRIVE AWAY        78560
6  2025  NO INJURY / DRIVE AWAY        77388
7  2026  NO INJURY / DRIVE AWAY        18547

### 11. Query to find the day of the week with the highest average crashes per hour.

In [19]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT 
                CASE CRASH_DAY_OF_WEEK
                    WHEN 1 THEN 'Sunday'
                    WHEN 2 THEN 'Monday'
                    WHEN 3 THEN 'Tuesday'
                    WHEN 4 THEN 'Wednesday'
                    WHEN 5 THEN 'Thursday'
                    WHEN 6 THEN 'Friday'
                    WHEN 7 THEN 'Saturday'
                END AS CRASH_DAY, ROUND(COUNT(*)/24,2) AS CRASH_TOTAL 
            FROM Traffic_Crashes_Analysis 
            GROUP BY CRASH_DAY_OF_WEEK 
            ORDER BY CRASH_TOTAL DESC
            LIMIT 1'''
cursor.execute(query)
df = read_sql(cursor)
df

  CRASH_DAY CRASH_TOTAL
1    Friday     4455.17

### 12. Query to Identify high-risk time slots by grouping hours into buckets (Morning, Afternoon, Evening, Night) and find which bucket has the highest injury crashes

In [20]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT TIMING, COUNT(*) AS INJURY_CRASHES
            FROM (
                SELECT 
                    CASE
                        WHEN crash_hour BETWEEN 5 AND 11 THEN 'Morning'
                        WHEN crash_hour BETWEEN 12 AND 16 THEN 'Afternoon'
                        WHEN crash_hour BETWEEN 17 AND 20 THEN 'Evening'
                        ELSE 'Night'
                    END AS TIMING
                FROM Traffic_Crashes_Analysis
                WHERE CRASH_TYPE = 'INJURY AND / OR TOW DUE TO CRASH'
            ) time_bucket
            GROUP BY TIMING
            ORDER BY INJURY_CRASHES DESC
            LIMIT 1'''
cursor.execute(query)
df = read_sql(cursor)
df

      TIMING  INJURY_CRASHES
1  Afternoon           55103

### 13. Query to find the top 3 contributing causes for each crash type.

In [21]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT CRASH_TYPE, PRIM_CONTRIBUTORY_CAUSE, CRASH_TOTAL
            FROM (
                SELECT CRASH_TYPE, PRIM_CONTRIBUTORY_CAUSE, COUNT(*) AS CRASH_TOTAL,
                    RANK() OVER (
                        PARTITION BY CRASH_TYPE
                        ORDER BY COUNT(*) DESC
                    ) AS rank_num
                FROM Traffic_Crashes_Analysis
                GROUP BY CRASH_TYPE, PRIM_CONTRIBUTORY_CAUSE
            ) ranking
            WHERE rank_num <= 3
            ORDER BY CRASH_TYPE, CRASH_TOTAL DESC'''
cursor.execute(query)
df = read_sql(cursor)
df

,CRASH_TYPE,PRIM_CONTRIBUTORY_CAUSE,CRASH_TOTAL
1,INJURY AND / OR TOW DUE TO CRASH,UNABLE TO DETERMINE,66377
2,INJURY AND / OR TOW DUE TO CRASH,FAILING TO YIELD RIGHT-OF-WAY,31840
3,INJURY AND / OR TOW DUE TO CRASH,FAILING TO REDUCE SPEED TO AVOID CRASH,13224
4,NO INJURY / DRIVE AWAY,UNABLE TO DETERMINE,206391
5,NO INJURY / DRIVE AWAY,FOLLOWING TOO CLOSELY,45964
6,NO INJURY / DRIVE AWAY,FAILING TO YIELD RIGHT-OF-WAY,41573

### 14. Query to calculate the year-over-year growth rate of crashes.

In [22]:
connection = makeConnection()
cursor = connection.cursor()
query = '''WITH YEARLY_CRASHES AS (
                SELECT year AS YEAR, COUNT(*) AS CRASH_TOTAL
                FROM Traffic_Crashes_Analysis
                GROUP BY year)
            SELECT YEAR, CRASH_TOTAL, LAG(CRASH_TOTAL) OVER (ORDER BY year) AS PREVIOUS_YEAR_CRASHES,
                ROUND(((CRASH_TOTAL - LAG(CRASH_TOTAL) OVER (ORDER BY year)) * 100.0) / 
                    LAG(CRASH_TOTAL) OVER (ORDER BY year), 2) AS YEAR_OVER_YEAR_GROWTH_RATE
            FROM YEARLY_CRASHES
            ORDER BY year'''
cursor.execute(query)
df = read_sql(cursor)
df

   YEAR  CRASH_TOTAL  PREVIOUS_YEAR_CRASHES YEAR_OVER_YEAR_GROWTH_RATE
1  2020        91509                    NaN                       None
2  2021       107937                91509.0                      17.95
3  2022       107462               107937.0                      -0.44
4  2023       109714               107462.0                       2.10
5  2024       110853               109714.0                       1.04
6  2025       107965               110853.0                      -2.61
7  2026        25494               107965.0                     -76.39

### 15. Query to identify hotspot zones by grouping nearby locations (round latitude & longitude to 2 decimal places) and find top 10 zones with highest crashes

In [23]:
connection = makeConnection()
cursor = connection.cursor()
query = '''SELECT ROUND(LATITUDE, 2) AS LATITUDE_ZONE, ROUND(LONGITUDE, 2) AS LONGITUDE_ZONE, COUNT(*) AS CRASH_TOTAL
            FROM Traffic_Crashes_Analysis
            GROUP BY ROUND(LATITUDE, 2), ROUND(LONGITUDE, 2)
            ORDER BY CRASH_TOTAL DESC
            LIMIT 10'''
cursor.execute(query)
df = read_sql(cursor)
df

    LATITUDE_ZONE  LONGITUDE_ZONE  CRASH_TOTAL
1           41.89          -87.63         7633
2           41.88          -87.63         5552
3           41.89          -87.62         5550
4           41.90          -87.62         5049
5           41.88          -87.62         4272
6           41.88          -87.64         3951
7           41.90          -87.63         3935
8           41.99          -87.66         3392
9           41.89          -87.64         3158
10          41.87          -87.64         3111